name: Deploy S3

on:
  push:
    branches:
      - develop
jobs:
  check-application:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Push to S3
        uses: reggionick/s3-deploy@v3
        with:
          folder: .
          bucket: areadesenvolvedor-versions
          bucket-region: us-east-2
          invalidation: /
          delete-removed: true
          no-cache: true
          private: true
          filesToInclude: ".*/*,*/*,**"
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          
